---
name: MCPEToDiscord
author: JaxkDev
version: 1.4.1
api: 3.0.0
main: Jack\DiscordMCPE\Main

commands:
  mcpediscord:
    description: Discord commands use /discord help for all cmds
    permission: op
    usage: /discord help
    default: op
...
